### ISSUE TITLE
Add Icons/pictograms to links on the front page 

### ISSUE THREAD

**Issue by ulf1** [hzi-braunschweig/serohub#62]
for these links
![image](https://user-images.githubusercontent.com/8018044/86221939-dcf04600-bb85-11ea-902a-33b308bc9491.png)

fontawesome examples
- blog (news): https://fontawesome.com/icons/newspaper?style=regular
- studies: https://fontawesome.com/icons/vial?style=solid
- publication: https://fontawesome.com/icons/file-alt?style=regular

**Comment by ulf1** [comment]
Keep it simple.
Add the icon on the left, as column maybe.
Icon should look big so that user can see it more easily.

**Comment by ulf1** [comment]
FYI the website uses FontAwesome 4.6.3

**Comment by Candice-Louw** [comment]
FontAwesome v4 icons chosen as follows:
- Blog (news): https://fontawesome.com/v4.7.0/icon/newspaper-o
- Studies: https://fontawesome.com/v4.7.0/icon/bar-chart
- Publication: https://fontawesome.com/v4.7.0/icon/file-text-o

Please post links if other icons are preferred/suggested instead of these.

<img width="823" alt="Annotation 2020-07-08 225612" src="https://user-images.githubusercontent.com/65529128/86969542-410a9f80-c16e-11ea-890c-b2294ff0c8c2.png">
